In [256]:
import pandas as pd
import numpy as np
import sklearn 
from sklearn import feature_selection

In [202]:
#Считывание
data_subs_f = pd.read_csv('subs_features_train.csv',';',decimal=',',parse_dates=['SNAP_DATE'])
data_subs_f.head(10)
#data_subs_f = data_subs_f.sort_values(['SNAP_DATE','SK_ID'])
data_subs_f = data_subs_f.sort_values(['SK_ID','SNAP_DATE'])
#data_subs_f = data_subs_f.sort_values([('SK_ID','SNAP_DATE')])
data_subs_f.head(10)
#data_subs_f['COM_CAT#1']

,SNAP_DATE,COM_CAT#1,SK_ID,COM_CAT#2,COM_CAT#3,BASE_TYPE,ACT,ARPU_GROUP,COM_CAT#7,COM_CAT#8,...,COM_CAT#25,COM_CAT#26,COM_CAT#27,COM_CAT#28,COM_CAT#29,COM_CAT#30,COM_CAT#31,COM_CAT#32,COM_CAT#33,COM_CAT#34
6503,2002-01-01,7,2,77,17,1,1,6.0,2,1318.0,...,1,0,0.001798,0.002754,0.000033,0.002331,0.022108,0.049189,0.27508,NaN
12304,2002-01-02,7,2,77,9,1,1,10.0,2,1318.0,...,1,1,0.003913,0.002139,0.000018,0.001954,0.054871,0.049189,0.27508,NaN
24981,2002-01-03,7,2,77,10,1,1,10.0,2,1318.0,...,1,1,0.002070,0.009867,0.000050,0.002785,0.029765,0.049189,0.27508,NaN
21704,2002-01-04,7,2,77,11,1,1,8.0,2,1318.0,...,1,1,0.006520,0.001894,0.000010,0.001709,0.022772,0.049189,0.27508,9.0
29381,2002-01-05,7,2,77,12,1,1,9.0,2,1318.0,...,1,1,0.001801,0.011187,0.000081,0.002441,0.018126,0.049189,0.27508,9.0
21807,2001-01-09,4,3,51,17,1,1,5.0,2,742.0,...,1,0,0.000000,0.000558,0.000019,0.000000,0.000205,0.049189,0.27508,NaN
14399,2001-01-10,4,3,51,9,1,1,8.0,2,742.0,...,1,1,0.000625,0.005613,0.001211,0.000000,0.002386,0.049189,0.27508,NaN
26898,2001-01-11,4,3,51,10,1,1,7.0,2,742.0,...,1,1,0.012354,0.029096,0.001411,0.000000,0.016379,0.049189,0.27508,NaN
24566,2001-01-12,4,3,51,11,1,1,8.0,2,742.0,...,1,1,0.020497,0.046781,0.000861,0.000000,0.026669,0.049189,0.27508,9.0
24326,2002-01-01,4,3,51,12,1,1,7.0,2,742.0,...,1,1,0.002012,0.001330,0.000636,0.000000,0.001456,0.049189,0.27508,9.0

In [203]:
data_subs_f.head(15)

,SNAP_DATE,COM_CAT#1,SK_ID,COM_CAT#2,COM_CAT#3,BASE_TYPE,ACT,ARPU_GROUP,COM_CAT#7,COM_CAT#8,...,COM_CAT#25,COM_CAT#26,COM_CAT#27,COM_CAT#28,COM_CAT#29,COM_CAT#30,COM_CAT#31,COM_CAT#32,COM_CAT#33,COM_CAT#34
6503,2002-01-01,7,2,77,17,1,1,6.0,2,1318.0,...,1,0,0.001798,0.002754,0.000033,0.002331,0.022108,0.049189,0.27508,NaN
12304,2002-01-02,7,2,77,9,1,1,10.0,2,1318.0,...,1,1,0.003913,0.002139,0.000018,0.001954,0.054871,0.049189,0.27508,NaN
24981,2002-01-03,7,2,77,10,1,1,10.0,2,1318.0,...,1,1,0.002070,0.009867,0.000050,0.002785,0.029765,0.049189,0.27508,NaN
21704,2002-01-04,7,2,77,11,1,1,8.0,2,1318.0,...,1,1,0.006520,0.001894,0.000010,0.001709,0.022772,0.049189,0.27508,9.0
29381,2002-01-05,7,2,77,12,1,1,9.0,2,1318.0,...,1,1,0.001801,0.011187,0.000081,0.002441,0.018126,0.049189,0.27508,9.0
21807,2001-01-09,4,3,51,17,1,1,5.0,2,742.0,...,1,0,0.000000,0.000558,0.000019,0.000000,0.000205,0.049189,0.27508,NaN
14399,2001-01-10,4,3,51,9,1,1,8.0,2,742.0,...,1,1,0.000625,0.005613,0.001211,0.000000,0.002386,0.049189,0.27508,NaN
26898,2001-01-11,4,3,51,10,1,1,7.0,2,742.0,...,1,1,0.012354,0.029096,0.001411,0.000000,0.016379,0.049189,0.27508,NaN
24566,2001-01-12,4,3,51,11,1,1,8.0,2,742.0,...,1,1,0.020497,0.046781,0.000861,0.000000,0.026669,0.049189,0.27508,9.0
24326,2002-01-01,4,3,51,12,1,1,7.0,2,742.0,...,1,1,0.002012,0.001330,0.000636,0.000000,0.001456,0.049189,0.27508,9.0
29547,2002-01-02,4,3,51,13,1,1,5.0,2,742.0,...,1,1,0.001383,0.008069,0.000969,0.000000,0.003919,0.049189,0.27508,9.0
14397,2002-01-03,4,3,51,14,2,1,12.0,2,742.0,...,1,1,0.001214,0.008199,0.001501,0.000000,0.002942,0.049189,0.27508,9.0
37161,2002-01-04,4,3,51,15,2,1,12.0,2,742.0,...,1,1,0.018385,0.037212,0.002040,0.000000,0.020871,0.049189,0.27508,9.0
14398,2002-01-05,4,3,51,16,2,1,10.0,2,827.0,...,1,1,0.022981,0.054331,0.000104,0.000627,0.029686,0.049189,0.27508,9.0
40584,2001-01-06,8,4,12,3,2,1,6.0,3,1268.0,...,1,1,0.003437,0.014412,0.000000,0.000000,0.045359,0.049189,0.27508,3.0

In [244]:
print ("Kolvo priznakov s null = ",test.index[data_subs_f.isnull().any()].size )
# Проверка незаполненных значений
print (data_subs_f.isnull().any())
#test = data_subs_f.isnull().any()

('Kolvo priznakov s null = ', 5)
SNAP_DATE           False
COM_CAT#1           False
SK_ID               False
COM_CAT#2           False
COM_CAT#3           False
BASE_TYPE           False
ACT                 False
ARPU_GROUP           True
COM_CAT#7           False
COM_CAT#8            True
DEVICE_TYPE_ID       True
INTERNET_TYPE_ID     True
REVENUE             False
ITC                 False
VAS                 False
RENT_CHANNEL        False
ROAM                False
COST                False
COM_CAT#17          False
COM_CAT#18          False
COM_CAT#19          False
COM_CAT#20          False
COM_CAT#21          False
COM_CAT#22          False
COM_CAT#23          False
COM_CAT#25          False
COM_CAT#26          False
COM_CAT#27          False
COM_CAT#28          False
COM_CAT#29          False
COM_CAT#30          False
COM_CAT#31          False
COM_CAT#32          False
COM_CAT#33          False
COM_CAT#34           True
dtype: bool

C:\Users\DAVasiliev\AppData\Local\Continuum\Anaconda2\lib\site-packages\pandas\core\indexes\base.py:1650: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 36 but corresponding boolean dimension is 35
  result = getitem(key)

In [220]:
# Посмотреть на них
data_subs_f.loc[data_subs_f['ARPU_GROUP'].isnull()]

,SNAP_DATE,COM_CAT#1,SK_ID,COM_CAT#2,COM_CAT#3,BASE_TYPE,ACT,ARPU_GROUP,COM_CAT#7,COM_CAT#8,...,COM_CAT#25,COM_CAT#26,COM_CAT#27,COM_CAT#28,COM_CAT#29,COM_CAT#30,COM_CAT#31,COM_CAT#32,COM_CAT#33,COM_CAT#34
35605,2002-01-05,2,546,37,1,2,1,NaN,1,73.0,...,1,1,0.000254,0.000000,0.000000,0.000000,0.027010,0.049189,0.275080,10.0
20410,2002-01-04,1,804,30,5,2,1,NaN,7,595.0,...,1,1,0.024900,0.025854,0.000000,0.000000,0.027178,0.049189,0.275080,10.0
30089,2001-01-08,7,1049,49,5,2,1,NaN,2,1310.0,...,1,1,0.009178,0.016089,0.000750,0.000000,0.033953,0.049189,0.275080,9.0
3316,2001-01-12,1,1307,30,5,2,1,NaN,2,1319.0,...,1,1,0.027357,0.030432,0.000068,0.000000,0.072117,0.049189,0.292375,8.0
12754,2002-01-02,2,1860,18,1,2,1,NaN,1,1373.0,...,1,1,0.011305,0.027390,0.000471,0.002619,0.035075,0.049189,0.275080,9.0
18755,2001-01-09,6,2041,35,11,1,1,NaN,2,963.0,...,1,1,0.000841,0.014601,0.004007,0.000000,0.061010,0.049189,0.275080,6.0
21132,2001-01-09,5,2149,33,5,2,1,NaN,1,1324.0,...,1,1,0.062624,0.073696,0.001631,0.000000,0.119626,0.049189,0.275080,1.0
12016,2002-01-01,5,2321,60,5,2,1,NaN,1,502.0,...,1,1,0.005919,0.003403,0.000000,0.000000,0.021514,0.049189,0.275080,9.0
5515,2002-01-02,6,2372,2,15,2,1,NaN,2,1278.0,...,1,1,0.007832,0.002869,0.069380,0.024238,0.004839,0.049189,0.275080,2.0
4129,2001-01-12,3,2839,65,10,1,0,NaN,6,1678.0,...,1,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.049189,0.275080,NaN
37005,2001-01-08,7,3092,77,4,2,1,NaN,1,126.0,...,1,1,0.029972,0.037138,0.000058,0.002832,0.049507,0.049189,0.275080,1.0
6914,2002-01-01,5,3275,41,5,2,1,NaN,1,1637.0,...,1,1,0.014344,0.037573,0.000773,0.003836,0.036162,0.049189,0.275080,2.0
20278,2002-01-04,3,3278,20,5,2,1,NaN,2,126.0,...,1,1,0.003068,0.001742,0.007415,0.023194,0.026995,0.049189,0.275080,2.0
6066,2002-01-04,6,3477,21,16,2,1,NaN,2,847.0,...,1,1,0.020298,0.053484,0.000112,0.003682,0.050317,0.049189,0.275080,2.0
11403,2001-01-12,5,3716,4,2,2,1,NaN,2,326.0,...,1,1,0.005045,0.001954,0.023441,0.000000,0.012833,0.049189,0.340526,8.0
22888,2002-01-05,4,3900,36,5,2,1,NaN,4,600.0,...,1,1,0.011376,0.000000,0.000000,0.000000,0.010400,0.049189,0.275080,10.0
33327,2002-01-02,4,4429,9,2,2,1,NaN,2,1315.0,...,1,1,0.008916,0.024606,0.011591,0.000000,0.051788,0.049189,0.275080,9.0
34758,2002-01-01,1,4681,30,5,2,1,NaN,1,1513.0,...,1,1,0.005908,0.009209,0.000040,0.000052,0.010279,0.051331,0.286408,9.0

In [245]:
# Число незаполненных атрибутов в конкретном столбце
print len(data_subs_f.index[data_subs_f['ARPU_GROUP'].isnull()].tolist())
print len(data_subs_f.index[data_subs_f['COM_CAT#8'].isnull()].tolist())
print len(data_subs_f.index[data_subs_f['DEVICE_TYPE_ID'].isnull()].tolist())
print len(data_subs_f.index[data_subs_f['INTERNET_TYPE_ID'].isnull()].tolist())
print len(data_subs_f.index[data_subs_f['COM_CAT#34'].isnull()].tolist())

18
86
86
86
1390

In [227]:
data_subs_f.dtypes

SNAP_DATE           datetime64[ns]
COM_CAT#1                    int64
SK_ID                        int64
COM_CAT#2                    int64
COM_CAT#3                    int64
BASE_TYPE                    int64
ACT                          int64
ARPU_GROUP                 float64
COM_CAT#7                    int64
COM_CAT#8                  float64
DEVICE_TYPE_ID             float64
INTERNET_TYPE_ID           float64
REVENUE                    float64
ITC                        float64
VAS                        float64
RENT_CHANNEL               float64
ROAM                       float64
COST                       float64
COM_CAT#17                 float64
COM_CAT#18                 float64
COM_CAT#19                 float64
COM_CAT#20                 float64
COM_CAT#21                 float64
COM_CAT#22                 float64
COM_CAT#23                 float64
COM_CAT#25                   int64
COM_CAT#26                   int64
COM_CAT#27                 float64
COM_CAT#28                 float64
COM_CAT#29                 float64
COM_CAT#30                 float64
COM_CAT#31                 float64
COM_CAT#32                 float64
COM_CAT#33                 float64
COM_CAT#34                 float64
dtype: object

In [276]:
# Дропнем 24 там везде 31 декабря - непонятная дата
data_subs_f = data_subs_f.drop('COM_CAT#24', 1)

In [242]:
# Разбиение на категориальные и числовые
numeric_cols = ['COM_CAT#8','REVENUE','ITC','VAS','RENT_CHANNEL','COST',
                'COM_CAT#17','COM_CAT#20','COM_CAT#21','COM_CAT#22','COM_CAT#23',
               'COM_CAT#27','COM_CAT#28','COM_CAT#29','COM_CAT#30','COM_CAT#31']
categorical_cols = list(set(data_subs_f.columns.values.tolist()) - set(numeric_cols))

In [243]:
categorical_cols

['COM_CAT#2',
 'INTERNET_TYPE_ID',
 'SK_ID',
 'COM_CAT#34',
 'COM_CAT#3',
 'ROAM',
 'COM_CAT#26',
 'BASE_TYPE',
 'COM_CAT#32',
 'COM_CAT#33',
 'ARPU_GROUP',
 'COM_CAT#1',
 'COM_CAT#25',
 'COM_CAT#7',
 'SNAP_DATE',
 'ACT',
 'DEVICE_TYPE_ID',
 'COM_CAT#18',
 'COM_CAT#19']

In [271]:
X = data_subs_f[categorical_cols]

In [272]:
X_test = X[['SK_ID','COM_CAT#18','COM_CAT#19','COM_CAT#32','COM_CAT#33']]

In [282]:
print X_test.nunique()
print X_test.shape

SK_ID         3622
COM_CAT#18     775
COM_CAT#19     114
COM_CAT#32    1637
COM_CAT#33    2606
dtype: int64
(40638, 5)

In [265]:
selector = sklearn.feature_selection.VarianceThreshold()

In [266]:
selector.fit_transform(X_test)

array([[  2.00000000e+00,   0.00000000e+00,   1.42530000e-02,
          4.91890000e-02,   2.75080000e-01],
       [  2.00000000e+00,   0.00000000e+00,   1.42530000e-02,
          4.91890000e-02,   2.75080000e-01],
       [  2.00000000e+00,   0.00000000e+00,   1.42530000e-02,
          4.91890000e-02,   2.75080000e-01],
       ...,
       [  4.70100000e+03,   0.00000000e+00,   1.42530000e-02,
          4.91890000e-02,   2.75080000e-01],
       [  4.70100000e+03,   0.00000000e+00,   1.42530000e-02,
          4.91890000e-02,   2.75080000e-01],
       [  4.70100000e+03,   0.00000000e+00,   1.42530000e-02,
          4.91890000e-02,   2.75080000e-01]])

In [248]:
data_subs_f[['COM_CAT#18','COM_CAT#19','COM_CAT#32','COM_CAT#33']]

       COM_CAT#18  COM_CAT#19  COM_CAT#32  COM_CAT#33
6503          0.0    0.014253    0.049189    0.275080
12304         0.0    0.014253    0.049189    0.275080
24981         0.0    0.014253    0.049189    0.275080
21704         0.0    0.014253    0.049189    0.275080
29381         0.0    0.014253    0.049189    0.275080
21807         0.0    0.014253    0.049189    0.275080
14399         0.0    0.014253    0.049189    0.275080
26898         0.0    0.014253    0.049189    0.275080
24566         0.0    0.014253    0.049189    0.275080
24326         0.0    0.014253    0.049189    0.275080
29547         0.0    0.014253    0.049189    0.275080
14397         0.0    0.014253    0.049189    0.275080
37161         0.0    0.014253    0.049189    0.275080
14398         0.0    0.014253    0.049189    0.275080
40584         0.0    0.014253    0.049189    0.275080
27649         0.0    0.014253    0.049189    0.275080
25226         0.0    0.014253    0.049189    0.275080
12444         0.0    0.014253    0.049189    0.275080
3782          0.0    0.014253    0.049189    0.275080
25244         0.0    0.014253    0.049189    0.275080
40589         0.0    0.014253    0.049189    0.275080
22638         0.0    0.014253    0.049189    0.275080
4929          0.0    0.014253    0.049189    0.275080
6334          0.0    0.014253    0.049189    0.275080
19981         0.0    0.014253    0.049189    0.275080
36777         0.0    0.014253    0.049189    0.275080
34109         0.0    0.014253    0.049189    0.275080
33549         0.0    0.014253    0.049189    0.275080
21396         0.0    0.014253    0.049189    0.275080
28879         0.0    0.014253    0.049189    0.275080
...           ...         ...         ...         ...
30847         0.0    0.014253    0.049189    0.275080
38512         0.0    0.014253    0.049189    0.275080
2941          0.0    0.014253    0.049189    0.275080
35988         0.0    0.014253    0.049189    0.275080
23236         0.0    0.014253    0.049189    0.275080
2902          0.0    0.014253    0.049189    0.275080
12244         0.0    0.014253    0.049189    0.275080
14131         0.0    0.014253    0.049189    0.275080
17274         0.0    0.014253    0.049189    0.394246
35091         0.0    0.014253    0.049189    0.275080
7973          0.0    0.014253    0.049189    0.275080
4584          0.0    0.014253    0.049189    0.275080
10694         0.0    0.014253    0.049189    0.275080
1471          0.0    0.014253    0.049189    0.275080
30931         0.0    0.014253    0.049189    0.275080
24899         0.0    0.014253    0.049189    0.275080
22385         0.0    0.014253    0.049189    0.275080
16625         0.0    0.014253    0.049189    0.275080
39093         0.0    0.014253    0.049189    0.275080
28881         0.0    0.014253    0.049189    0.275080
23900         0.0    0.014253    0.049189    0.275080
28878         0.0    0.014253    0.049189    0.275080
16109         0.0    0.014253    0.049189    0.275080
39067         0.0    0.014253    0.049189    0.275080
6142          0.0    0.014253    0.049189    0.275080
28887         0.0    0.014253    0.049189    0.275080
21397         0.0    0.014253    0.049189    0.275080
36500         0.0    0.014253    0.049189    0.275080
36694         0.0    0.014253    0.049189    0.275080
8560          0.0    0.014253    0.049189    0.275080

[40638 rows x 4 columns]

In [240]:
data_subs_f.iloc[0:15,22:]

,COM_CAT#21,COM_CAT#22,COM_CAT#23,COM_CAT#25,COM_CAT#26,COM_CAT#27,COM_CAT#28,COM_CAT#29,COM_CAT#30,COM_CAT#31,COM_CAT#32,COM_CAT#33,COM_CAT#34
6503,0.016110,0.701424,0.118129,1,0,0.001798,0.002754,0.000033,0.002331,0.022108,0.049189,0.27508,NaN
12304,0.016110,0.707528,0.134836,1,1,0.003913,0.002139,0.000018,0.001954,0.054871,0.049189,0.27508,NaN
24981,0.016110,0.706893,0.133897,1,1,0.002070,0.009867,0.000050,0.002785,0.029765,0.049189,0.27508,NaN
21704,0.016110,0.704850,0.126587,1,1,0.006520,0.001894,0.000010,0.001709,0.022772,0.049189,0.27508,9.0
29381,0.016110,0.705129,0.129093,1,1,0.001801,0.011187,0.000081,0.002441,0.018126,0.049189,0.27508,9.0
21807,0.016110,0.700528,0.115501,1,0,0.000000,0.000558,0.000019,0.000000,0.000205,0.049189,0.27508,NaN
14399,0.024902,0.700275,0.127683,1,1,0.000625,0.005613,0.001211,0.000000,0.002386,0.049189,0.27508,NaN
26898,0.020543,0.699858,0.121696,1,1,0.012354,0.029096,0.001411,0.000000,0.016379,0.049189,0.27508,NaN
24566,0.021316,0.699855,0.123837,1,1,0.020497,0.046781,0.000861,0.000000,0.026669,0.049189,0.27508,9.0
24326,0.020506,0.700891,0.122636,1,1,0.002012,0.001330,0.000636,0.000000,0.001456,0.049189,0.27508,9.0
29547,0.018197,0.699068,0.115193,1,1,0.001383,0.008069,0.000969,0.000000,0.003919,0.049189,0.27508,9.0
14397,0.025530,0.714906,0.190338,1,1,0.001214,0.008199,0.001501,0.000000,0.002942,0.049189,0.27508,9.0
37161,0.021875,0.706658,0.150274,1,1,0.018385,0.037212,0.002040,0.000000,0.020871,0.049189,0.27508,9.0
14398,0.021818,0.701068,0.128884,1,1,0.022981,0.054331,0.000104,0.000627,0.029686,0.049189,0.27508,9.0
40584,0.016110,0.700696,0.117744,1,1,0.003437,0.014412,0.000000,0.000000,0.045359,0.049189,0.27508,3.0

In [217]:

# Попытки создания словаря
data_subs_f
d = dict(data_subs_f['ARPU_GROUP'])

In [218]:
d

{0: 6.0,
 1: 3.0,
 2: 11.0,
 3: 12.0,
 4: 12.0,
 5: 9.0,
 6: 7.0,
 7: 10.0,
 8: 3.0,
 9: 8.0,
 10: 6.0,
 11: 12.0,
 12: 1.0,
 13: 4.0,
 14: 8.0,
 15: 9.0,
 16: 2.0,
 17: 7.0,
 18: 12.0,
 19: 10.0,
 20: 1.0,
 21: 11.0,
 22: 5.0,
 23: 7.0,
 24: 8.0,
 25: 6.0,
 26: 12.0,
 27: 12.0,
 28: 11.0,
 29: 10.0,
 30: 9.0,
 31: 10.0,
 32: 6.0,
 33: 8.0,
 34: 1.0,
 35: 7.0,
 36: 6.0,
 37: 9.0,
 38: 5.0,
 39: 7.0,
 40: 8.0,
 41: 6.0,
 42: 12.0,
 43: 8.0,
 44: 5.0,
 45: 5.0,
 46: 8.0,
 47: 12.0,
 48: 7.0,
 49: 6.0,
 50: 6.0,
 51: 6.0,
 52: 7.0,
 53: 8.0,
 54: 10.0,
 55: 5.0,
 56: 4.0,
 57: 9.0,
 58: 5.0,
 59: 6.0,
 60: 7.0,
 61: 7.0,
 62: 7.0,
 63: 8.0,
 64: 5.0,
 65: 9.0,
 66: 7.0,
 67: 12.0,
 68: 9.0,
 69: 12.0,
 70: 7.0,
 71: 8.0,
 72: 7.0,
 73: 11.0,
 74: 5.0,
 75: 12.0,
 76: 6.0,
 77: 5.0,
 78: 6.0,
 79: 7.0,
 80: 1.0,
 81: 12.0,
 82: 9.0,
 83: 1.0,
 84: 12.0,
 85: 3.0,
 86: 8.0,
 87: 7.0,
 88: 5.0,
 89: 6.0,
 90: 9.0,
 91: 12.0,
 92: 7.0,
 93: 12.0,
 94: 7.0,
 95: 1.0,
 96: 12.0,
 97: 8.0,
 98: 12.0,
 99: 7.0,
 100: 12.0,
 101: 7.0,
 102: 8.0,
 103: 10.0,
 104: 9.0,
 105: 5.0,
 106: 12.0,
 107: 3.0,
 108: 5.0,
 109: 8.0,
 110: 5.0,
 111: 7.0,
 112: 1.0,
 113: 10.0,
 114: 7.0,
 115: 10.0,
 116: 12.0,
 117: 4.0,
 118: 1.0,
 119: 3.0,
 120: 6.0,
 121: 5.0,
 122: 8.0,
 123: 5.0,
 124: 12.0,
 125: 12.0,
 126: 12.0,
 127: 4.0,
 128: 12.0,
 129: 12.0,
 130: 12.0,
 131: 12.0,
 132: 8.0,
 133: 9.0,
 134: 9.0,
 135: 11.0,
 136: 10.0,
 137: 12.0,
 138: 10.0,
 139: 5.0,
 140: 10.0,
 141: 6.0,
 142: 10.0,
 143: 12.0,
 144: 8.0,
 145: 2.0,
 146: 12.0,
 147: 12.0,
 148: 1.0,
 149: 1.0,
 150: 7.0,
 151: 11.0,
 152: 9.0,
 153: 6.0,
 154: 8.0,
 155: 8.0,
 156: 7.0,
 157: 6.0,
 158: 6.0,
 159: 12.0,
 160: 12.0,
 161: 5.0,
 162: 10.0,
 163: 2.0,
 164: 5.0,
 165: 10.0,
 166: 11.0,
 167: 6.0,
 168: 12.0,
 169: 12.0,
 170: 12.0,
 171: 1.0,
 172: 8.0,
 173: 8.0,
 174: 8.0,
 175: 7.0,
 176: 8.0,
 177: 6.0,
 178: 11.0,
 179: 5.0,
 180: 12.0,
 181: 6.0,
 182: 9.0,
 183: 8.0,
 184: 12.0,
 185: 9.0,
 186: 12.0,
 187: 12.0,
 188: 5.0,
 189: 8.0,
 190: 7.0,
 191: 8.0,
 192: 2.0,
 193: 6.0,
 194: 3.0,
 195: 12.0,
 196: 8.0,
 197: 10.0,
 198: 3.0,
 199: 8.0,
 200: 7.0,
 201: 6.0,
 202: 10.0,
 203: 4.0,
 204: 12.0,
 205: 9.0,
 206: 3.0,
 207: 5.0,
 208: 12.0,
 209: 8.0,
 210: 1.0,
 211: 5.0,
 212: 12.0,
 213: 8.0,
 214: 8.0,
 215: 8.0,
 216: 7.0,
 217: 10.0,
 218: 4.0,
 219: 5.0,
 220: 3.0,
 221: 4.0,
 222: 8.0,
 223: 5.0,
 224: 8.0,
 225: 6.0,
 226: 8.0,
 227: 11.0,
 228: 4.0,
 229: 4.0,
 230: 9.0,
 231: 10.0,
 232: 1.0,
 233: 7.0,
 234: 11.0,
 235: 8.0,
 236: 7.0,
 237: 8.0,
 238: 8.0,
 239: 10.0,
 240: 3.0,
 241: 9.0,
 242: 8.0,
 243: 12.0,
 244: 11.0,
 245: 7.0,
 246: 12.0,
 247: 4.0,
 248: 12.0,
 249: 8.0,
 250: 10.0,
 251: 11.0,
 252: 11.0,
 253: 10.0,
 254: 8.0,
 255: 12.0,
 256: 1.0,
 257: 9.0,
 258: 8.0,
 259: 8.0,
 260: 4.0,
 261: 12.0,
 262: 8.0,
 263: 7.0,
 264: 6.0,
 265: 5.0,
 266: 11.0,
 267: 2.0,
 268: 8.0,
 269: 2.0,
 270: 6.0,
 271: 8.0,
 272: 6.0,
 273: 7.0,
 274: 10.0,
 275: 12.0,
 276: 9.0,
 277: 7.0,
 278: 5.0,
 279: 4.0,
 280: 12.0,
 281: 12.0,
 282: 1.0,
 283: 7.0,
 284: 10.0,
 285: 8.0,
 286: 12.0,
 287: 10.0,
 288: 7.0,
 289: 1.0,
 290: 7.0,
 291: 10.0,
 292: 12.0,
 293: 9.0,
 294: 6.0,
 295: 12.0,
 296: 7.0,
 297: 2.0,
 298: 12.0,
 299: 12.0,
 300: 12.0,
 301: 12.0,
 302: 4.0,
 303: 7.0,
 304: 12.0,
 305: 11.0,
 306: 6.0,
 307: 10.0,
 308: 12.0,
 309: 9.0,
 310: 12.0,
 311: 4.0,
 312: 10.0,
 313: 12.0,
 314: 5.0,
 315: 8.0,
 316: 6.0,
 317: 11.0,
 318: 11.0,
 319: 2.0,
 320: 10.0,
 321: 7.0,
 322: 11.0,
 323: 6.0,
 324: 6.0,
 325: 5.0,
 326: 6.0,
 327: 8.0,
 328: 1.0,
 329: 8.0,
 330: 5.0,
 331: 8.0,
 332: 12.0,
 333: 12.0,
 334: 10.0,
 335: 12.0,
 336: 6.0,
 337: 6.0,
 338: 10.0,
 339: 7.0,
 340: 7.0,
 341: 7.0,
 342: 2.0,
 343: 7.0,
 344: 12.0,
 345: 12.0,
 346: 5.0,
 347: 5.0,
 348: 6.0,
 349: 1.0,
 350: 12.0,
 351: 10.0,
 352: 5.0,
 353: 12.0,
 354: 12.0,
 355: 7.0,
 356: 12.0,
 357: 7.0,
 358: 5.0,
 359: 12.0,
 360: 4.0,
 361: 11.0,
 362: 12.0,
 363: 12.0,
 364: 8.0,
 365: 8.0,
 366: 9.0,
 367: 9.0,
 368: 7.0,
 369: 4.0,
 370: 10.0,
 371: 1.0,
 372: 1.0,
 373: 9.0,
 374: 7.0,
 375: 6.0,
 376: 5.0,
 377: 12.0,
 378: 7.0,
 379: 8.0,
 380: 4.0,
 381: 1.0,
 382: 12.0,
 383: 10.0,
 384: 3.0,
 385: 7.0,
 386: 4.0,
 387: 8.0,
 388: 8.0,
 389: 2.0,
 390: 3.0,
 391: 8.0,
 392: 10.0,
 393: 9.0,
 394: 6.0,
 395: 5.0,
 396: 8.0,
 397: 1.0,
 398: 10.0,
 399: 7.0,
 400: 8.0,
 401: 5.0,
 402: 8.0,
 403: 12.0,
 404: 2.0,
 405: 10.0,
 406: 4.0,
 407: 5.0,
 408: 10.0,
 409: 9.0,
 410: 7.0,
 411: 9.0,
 412: 5.0,
 413: 2.0,
 414: 1.0,
 415: 12.0,
 416: 11.0,
 417: 10.0,
 418: 1.0,
 419: 4.0,
 420: 6.0,
 421: 6.0,
 422: 6.0,
 423: 7.0,
 424: 5.0,
 425: 5.0,
 426: 6.0,
 427: 7.0,
 428: 9.0,
 429: 7.0,
 430: 3.0,
 431: 6.0,
 432: 12.0,
 433: 12.0,
 434: 5.0,
 435: 9.0,
 436: 10.0,
 437: 5.0,
 438: 12.0,
 439: 12.0,
 440: 12.0,
 441: 11.0,
 442: 12.0,
 443: 12.0,
 444: 7.0,
 445: 6.0,
 446: 6.0,
 447: 8.0,
 448: 7.0,
 449: 7.0,
 450: 4.0,
 451: 7.0,
 452: 10.0,
 453: 6.0,
 454: 12.0,
 455: 6.0,
 456: 5.0,
 457: 1.0,
 458: 9.0,
 459: 1.0,
 460: 6.0,
 461: 12.0,
 462: 4.0,
 463: 10.0,
 464: 9.0,
 465: 8.0,
 466: 1.0,
 467: 1.0,
 468: 12.0,
 469: 7.0,
 470: 4.0,
 471: 7.0,
 472: 1.0,
 473: 7.0,
 474: 12.0,
 475: 8.0,
 476: 12.0,
 477: 7.0,
 478: 12.0,
 479: 4.0,
 480: 8.0,
 481: 3.0,
 482: 5.0,
 483: 7.0,
 484: 12.0,
 485: 6.0,
 486: 8.0,
 487: 5.0,
 488: 12.0,
 489: 12.0,
 490: 4.0,
 491: 11.0,
 492: 3.0,
 493: 10.0,
 494: 5.0,
 495: 11.0,
 496: 12.0,
 497: 4.0,
 498: 5.0,
 499: 8.0,
 500: 2.0,
 501: 2.0,
 502: 12.0,
 503: 7.0,
 504: 6.0,
 505: 9.0,
 506: 12.0,
 507: 12.0,
 508: 12.0,
 509: 6.0,
 510: 9.0,
 511: 8.0,
 512: 10.0,
 513: 12.0,
 514: 10.0,
 515: 10.0,
 516: 12.0,
 517: 5.0,
 518: 12.0,
 519: 7.0,
 520: 6.0,
 521: 5.0,
 522: 5.0,
 523: 11.0,
 524: 7.0,
 525: 1.0,
 526: 7.0,
 527: 8.0,
 528: 10.0,
 529: 12.0,
 530: 6.0,
 531: 7.0,
 532: 7.0,
 533: 12.0,
 534: 6.0,
 535: 10.0,
 536: 11.0,
 537: 6.0,
 538: 8.0,
 539: 9.0,
 540: 6.0,
 541: 12.0,
 542: 6.0,
 543: 1.0,
 544: 9.0,
 545: 11.0,
 546: 11.0,
 547: 7.0,
 548: 8.0,
 549: 9.0,
 550: 6.0,
 551: 9.0,
 552: 10.0,
 553: 12.0,
 554: 6.0,
 555: 6.0,
 556: 4.0,
 557: 11.0,
 558: 11.0,
 559: 7.0,
 560: 7.0,
 561: 8.0,
 562: 11.0,
 563: 7.0,
 564: 11.0,
 565: 10.0,
 566: 5.0,
 567: 9.0,
 568: 2.0,
 569: 7.0,
 570: 2.0,
 571: 9.0,
 572: 7.0,
 573: 2.0,
 574: 8.0,
 575: 7.0,
 576: 6.0,
 577: 7.0,
 578: 7.0,
 579: 9.0,
 580: 4.0,
 581: 10.0,
 582: 12.0,
 583: 12.0,
 584: 12.0,
 585: 12.0,
 586: 1.0,
 587: 6.0,
 588: 12.0,
 589: 9.0,
 590: 8.0,
 591: 8.0,
 592: 8.0,
 593: 11.0,
 594: 8.0,
 595: 1.0,
 596: 9.0,
 597: 9.0,
 598: 10.0,
 599: 11.0,
 600: 10.0,
 601: 10.0,
 602: 1.0,
 603: 7.0,
 604: 12.0,
 605: 12.0,
 606: 9.0,
 607: 11.0,
 608: 8.0,
 609: 2.0,
 610: 8.0,
 611: 9.0,
 612: 12.0,
 613: 4.0,
 614: 6.0,
 615: 12.0,
 616: 12.0,
 617: 7.0,
 618: 4.0,
 619: 3.0,
 620: 6.0,
 621: 5.0,
 622: 8.0,
 623: 8.0,
 624: 3.0,
 625: 10.0,
 626: 11.0,
 627: 12.0,
 628: 12.0,
 629: 10.0,
 630: 5.0,
 631: 10.0,
 632: 10.0,
 633: 7.0,
 634: 10.0,
 635: 9.0,
 636: 12.0,
 637: 5.0,
 638: 8.0,
 639: 6.0,
 640: 7.0,
 641: 7.0,
 642: 10.0,
 643: 7.0,
 644: 12.0,
 645: 12.0,
 646: 12.0,
 647: 12.0,
 648: 5.0,
 649: 6.0,
 650: 12.0,
 651: 5.0,
 652: 10.0,
 653: 6.0,
 654: 2.0,
 655: 1.0,
 656: 10.0,
 657: 6.0,
 658: 7.0,
 659: 7.0,
 660: 5.0,
 661: 9.0,
 662: 8.0,
 663: 7.0,
 664: 5.0,
 665: 7.0,
 666: 10.0,
 667: 5.0,
 668: 12.0,
 669: 12.0,
 670: 4.0,
 671: 12.0,
 672: 12.0,
 673: 9.0,
 674: 10.0,
 675: 12.0,
 676: 8.0,
 677: 3.0,
 678: 3.0,
 679: 7.0,
 680: 7.0,
 681: 10.0,
 682: 7.0,
 683: 10.0,
 684: 11.0,
 685: 6.0,
 686: 7.0,
 687: 7.0,
 688: 6.0,
 689: 6.0,
 690: 5.0,
 691: 1.0,
 692: 4.0,
 693: 4.0,
 694: 8.0,
 695: 1.0,
 696: 9.0,
 697: 12.0,
 698: 2.0,
 699: 2.0,
 700: 12.0,
 701: 7.0,
 702: 8.0,
 703: 10.0,
 704: 9.0,
 705: 12.0,
 706: 6.0,
 707: 5.0,
 708: 7.0,
 709: 8.0,
 710: 9.0,
 711: 12.0,
 712: 4.0,
 713: 5.0,
 714: 12.0,
 715: 7.0,
 716: 2.0,
 717: 7.0,
 718: 1.0,
 719: 5.0,
 720: 10.0,
 721: 12.0,
 722: 5.0,
 723: 12.0,
 724: 12.0,
 725: 8.0,
 726: 12.0,
 727: 6.0,
 728: 12.0,
 729: 12.0,
 730: 9.0,
 731: 12.0,
 732: 11.0,
 733: 9.0,
 734: 9.0,
 735: 12.0,
 736: 5.0,
 737: 10.0,
 738: 8.0,
 739: 11.0,
 740: 8.0,
 741: 5.0,
 742: 2.0,
 743: 12.0,
 744: 11.0,
 745: 7.0,
 746: 3.0,
 747: 12.0,
 748: 5.0,
 749: 3.0,
 750: 12.0,
 751: 6.0,
 752: 12.0,
 753: 7.0,
 754: 4.0,
 755: 5.0,
 756: 10.0,
 757: 1.0,
 758: 12.0,
 759: 6.0,
 760: 12.0,
 761: 12.0,
 762: 12.0,
 763: 4.0,
 764: 7.0,
 765: 1.0,
 766: 1.0,
 767: 9.0,
 768: 12.0,
 769: 12.0,
 770: 7.0,
 771: 7.0,
 772: 12.0,
 773: 8.0,
 774: 10.0,
 775: 3.0,
 776: 4.0,
 777: 12.0,
 778: 7.0,
 779: 7.0,
 780: 9.0,
 781: 1.0,
 782: 9.0,
 783: 3.0,
 784: 8.0,
 785: 7.0,
 786: 12.0,
 787: 7.0,
 788: 5.0,
 789: 1.0,
 790: 9.0,
 791: 8.0,
 792: 4.0,
 793: 6.0,
 794: 4.0,
 795: 10.0,
 796: 3.0,
 797: 5.0,
 798: 9.0,
 799: 8.0,
 800: 8.0,
 801: 8.0,
 802: 6.0,
 803: 5.0,
 804: 12.0,
 805: 5.0,
 806: 9.0,
 807: 12.0,
 808: 9.0,
 809: 5.0,
 810: 6.0,
 811: 8.0,
 812: 5.0,
 813: 12.0,
 814: 3.0,
 815: 9.0,
 816: 8.0,
 817: 9.0,
 818: 11.0,
 819: 7.0,
 820: 11.0,
 821: 10.0,
 822: 1.0,
 823: 7.0,
 824: 9.0,
 825: 4.0,
 826: 10.0,
 827: 5.0,
 828: 12.0,
 829: 1.0,
 830: 6.0,
 831: 11.0,
 832: 12.0,
 833: 11.0,
 834: 12.0,
 835: 8.0,
 836: 5.0,
 837: 9.0,
 838: 9.0,
 839: 12.0,
 840: 12.0,
 841: 6.0,
 842: 12.0,
 843: 12.0,
 844: 9.0,
 845: 12.0,
 846: 6.0,
 847: 12.0,
 848: 9.0,
 849: 12.0,
 850: 7.0,
 851: 6.0,
 852: 7.0,
 853: 12.0,
 854: 10.0,
 855: 12.0,
 856: 12.0,
 857: 7.0,
 858: 8.0,
 859: 11.0,
 860: 6.0,
 861: 6.0,
 862: 3.0,
 863: 10.0,
 864: 6.0,
 865: 7.0,
 866: 11.0,
 867: 5.0,
 868: 11.0,
 869: 11.0,
 870: 2.0,
 871: 1.0,
 872: 12.0,
 873: 8.0,
 874: 10.0,
 875: 9.0,
 876: 4.0,
 877: 12.0,
 878: 10.0,
 879: 8.0,
 880: 4.0,
 881: 9.0,
 882: 10.0,
 883: 10.0,
 884: 6.0,
 885: 9.0,
 886: 3.0,
 887: 3.0,
 888: 10.0,
 889: 7.0,
 890: 5.0,
 891: 6.0,
 892: 12.0,
 893: 6.0,
 894: 9.0,
 895: 12.0,
 896: 11.0,
 897: 7.0,
 898: 6.0,
 899: 3.0,
 900: 9.0,
 901: 2.0,
 902: 11.0,
 903: 7.0,
 904: 9.0,
 905: 12.0,
 906: 5.0,
 907: 12.0,
 908: 5.0,
 909: 9.0,
 910: 8.0,
 911: 7.0,
 912: 7.0,
 913: 12.0,
 914: 10.0,
 915: 12.0,
 916: 12.0,
 917: 5.0,
 918: 5.0,
 919: 7.0,
 920: 10.0,
 921: 12.0,
 922: 6.0,
 923: 7.0,
 924: 2.0,
 925: 9.0,
 926: 9.0,
 927: 2.0,
 928: 12.0,
 929: 11.0,
 930: 12.0,
 931: 3.0,
 932: 12.0,
 933: 9.0,
 934: 6.0,
 935: 5.0,
 936: 11.0,
 937: 11.0,
 938: 8.0,
 939: 10.0,
 940: 8.0,
 941: 7.0,
 942: 9.0,
 943: 1.0,
 944: 6.0,
 945: 1.0,
 946: 9.0,
 947: 9.0,
 948: 1.0,
 949: 11.0,
 950: 10.0,
 951: 8.0,
 952: 10.0,
 953: 3.0,
 954: 6.0,
 955: 9.0,
 956: 12.0,
 957: 7.0,
 958: 12.0,
 959: 5.0,
 960: 12.0,
 961: 5.0,
 962: 10.0,
 963: 2.0,
 964: 12.0,
 965: 8.0,
 966: 9.0,
 967: 11.0,
 968: 6.0,
 969: 1.0,
 970: 7.0,
 971: 6.0,
 972: 8.0,
 973: 1.0,
 974: 5.0,
 975: 5.0,
 976: 10.0,
 977: 5.0,
 978: 12.0,
 979: 7.0,
 980: 1.0,
 981: 12.0,
 982: 9.0,
 983: 9.0,
 984: 12.0,
 985: 12.0,
 986: 8.0,
 987: 12.0,
 988: 6.0,
 989: 12.0,
 990: 6.0,
 991: 7.0,
 992: 12.0,
 993: 6.0,
 994: 7.0,
 995: 4.0,
 996: 7.0,
 997: 10.0,
 998: 2.0,
 999: 5.0,
 ...}